
package mx.bankaya.demo.pokemon.client.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PokemonPort", targetNamespace = "http://bankaya.mx/demos/web-service")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PokemonPort {


    /**
     * 
     * @param getPokemonRequest
     * @return
     *     returns mx.bankaya.demo.pokemon.client.soap.GetPokemonResponse
     */
    @WebMethod
    @WebResult(name = "getPokemonResponse", targetNamespace = "http://bankaya.mx/demos/web-service", partName = "getPokemonResponse")
    public GetPokemonResponse getPokemon(
        @WebParam(name = "getPokemonRequest", targetNamespace = "http://bankaya.mx/demos/web-service", partName = "getPokemonRequest")
        GetPokemonRequest getPokemonRequest);

}
